import { config } from "./config.js";
import { InputFile } from "grammy";

/**
 * Convert text to speech.
 * In production (Railway), uses Sarvam AI (bulbul:v3).
 * In local dev, uses the local Kokoro TTS server.
 * Returns a Buffer containing audio (Ogg or Wav), or null if TTS is unavailable.
 */
export async function textToSpeech(text: string): Promise<Buffer | null> {
  // Trim text to avoid generating excessively long audio
  const trimmed = text.slice(0, 2000);

  // ── Production: Sarvam AI ───────────────────────────────
  if (process.env.RAILWAY_ENVIRONMENT_NAME) {
    if (!config.sarvamApiKey) {
      console.warn("⚠️  TTS skipped: SARVAM_API_KEY is not set in production.");
      return null;
    }

    try {
      const res = await fetch("https://api.sarvam.ai/text-to-speech", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "api-subscription-key": config.sarvamApiKey
        },
        signal: AbortSignal.timeout(10_000),
        body: JSON.stringify({
          inputs: [trimmed],
          target_language_code: "en-IN",
          speaker: "amelia",
          pace: 1.0,
          enable_preprocessing: true,
          model: "bulbul:v3"
        })
      });

      if (!res.ok) {
        console.warn(`⚠️  Sarvam TTS Failed (${res.status}): ${await res.text()}`);
        return null;
      }

      const data = await res.json() as any;
      if (data.audios && data.audios[0]) {
        return Buffer.from(data.audios[0], "base64");
      }
      return null;
    } catch (error) {
      console.warn(`⚠️  Sarvam TTS Exception: ${error instanceof Error ? error.message : error}`);
      return null;
    }
  }

  // ── Local Development: Kokoro TTS ───────────────────────
  if (!config.kokoroUrl) return null;

  try {
    const response = await fetch(`${config.kokoroUrl}/tts`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      signal: AbortSignal.timeout(10_000),
      body: JSON.stringify({
        text: trimmed,
        voice: config.kokoroVoice,
        speed: 1.0,
      }),
    });

    if (!response.ok) {
      console.warn(`⚠️  Local TTS server returned ${response.status}: ${await response.text()}`);
      return null;
    }

    const arrayBuffer = await response.arrayBuffer();
    return Buffer.from(arrayBuffer);
  } catch (error) {
    console.warn(`⚠️  Local TTS unavailable: ${error instanceof Error ? error.message : error}`);
    return null;
  }
}

/**
 * Create a grammY InputFile from an audio buffer for sending as a voice message.
 */
export function audioToInputFile(buffer: Buffer): InputFile {
  return new InputFile(buffer, "voice.wav");
}

/**
 * Stream TTS for a sequence of sentences, yielding audio buffers as each is ready.
 * Uses Kokoro's /tts/stream endpoint in local dev, or falls back to batch TTS.
 * This allows sentence-level parallelism: TTS for sentence N starts while
 * sentence N+1 tokens are still being generated by the LLM.
 */
export async function* textToSpeechStream(
  sentences: AsyncIterable<string>,
): AsyncGenerator<Buffer> {
  for await (const sentence of sentences) {
    if (!sentence.trim()) continue;

    // Try Kokoro streaming endpoint for local dev, fall back to batch
    if (!process.env.RAILWAY_ENVIRONMENT_NAME && config.kokoroUrl) {
      try {
        const response = await fetch(`${config.kokoroUrl}/tts/stream`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text: sentence.slice(0, 500), voice: config.kokoroVoice, speed: 1.0 }),
        });

        if (response.ok && response.body) {
          // Parse length-prefixed WAV chunks
          const reader = response.body.getReader();
          let remainder = Buffer.alloc(0);

          while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            remainder = Buffer.concat([remainder, Buffer.from(value)]);

            // Extract complete frames
            while (remainder.length >= 4) {
              const frameLen = remainder.readUInt32BE(0);
              if (remainder.length < 4 + frameLen) break;
              const wavChunk = remainder.slice(4, 4 + frameLen);
              remainder = remainder.slice(4 + frameLen);
              yield wavChunk;
            }
          }
          continue;
        }
      } catch {
        // Fall through to batch TTS
      }
    }

    // Batch fallback (Sarvam in prod, Kokoro batch in dev)
    const audio = await textToSpeech(sentence);
    if (audio) yield audio;
  }
}
